### ISSUE TITLE
Unable to parse DailyMed label section data for some set IDs

### ISSUE THREAD

**Issue by krithika369** [pharmaDB/dailymed_data_processor#5]
Such as the labels for [this](https://dailymed.nlm.nih.gov/dailymed/getFile.cfm?type=zip&setid=1b5e2860-6855-4a65-8bbc-e064172a1adf&version=1) SPL set ID, since its format is different.

<img width="1066" alt="Screenshot 2021-04-02 at 11 14 29 PM" src="https://user-images.githubusercontent.com/23465343/113428602-a80d6a00-9409-11eb-8ed7-905fa2ed5942.png">

**Comment by TerryChau** [comment]
This should be addressed by [flat_labels](https://github.com/pharmaDB/dailymed_data_processor/pull/9)

**Comment by krithika369** [comment]
Thanks, @TerryChau !
